name = "mcp-monitor"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "14adde85f76060c6edef6f3239d36e6a"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "MCP_STATE"
id = "8d19a69ee3f7451f924c70f609c87a9b"
