name = "garza-health-monitor"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "14adde85f76060c6edef6f3239d36e6a"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "GARZA_STATE"
id = "cfb27b9cfcbe453080c1f18132da54d4"
