app = "garza-ears"
primary_region = "dfw"

[build]

[mounts]
  source = "garza_ears_data"
  destination = "/data"

[env]
  NODE_ENV = "production"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
